### ISSUE TITLE
Last pulls issues

### ISSUE THREAD

**Issue by LennyLip** [studyhub-co/physics-is-beautiful#107]
1. the extra closing span tag

https://github.com/nscozzaro/physics-is-beautiful/blob/117405d73eaa64bc2e5aae5ae86effde142f699f/blog/templates/blog/navbar.html#L70

2.  /templates/blog/navbar.html,  /templates/navbar.html and templates/allauth/account/base.html  almost identical. We have to use a DRY principle.

3. [DOM] Found 2 elements with non-unique id #id_remember: (More info: https://goo.gl/9p2vKq) <input type="checkbox" class="form-check" name="remember" id="id_remember"> <input type=​"checkbox" class=​"form-check" name=​"remember" id=​"id_remember"> 

(Sign Up / Sign in page)

4. https://github.com/nscozzaro/physics-is-beautiful/blob/master/blog/templates/blog/wordpairs.html#L4 

Block name must use the function naming rules: lowercase with words separated by underscores as necessary to improve readability.

5. https://github.com/nscozzaro/physics-is-beautiful/blob/master/blog/templates/blog/wordpairs.html#L7 css needs to move to /static/blog/style.css

6.  https://github.com/nscozzaro/physics-is-beautiful/blob/master/blog/views.py
all def (functions) also must use the function naming rules: lowercase with words separated by underscores. See pep8 for details.

7. I think we must avoid using id="navTopOfScreen" camel case in ids also. We need to convert all values of tags attributes to a uniform style. I suggest using BEM methodology  http://getbem.com/introduction/  , but we can use own style (e.g. lowercase with words separated by hyphens or underscores).

**Comment by nch0w** [comment]
I will fix those soon.

**Comment by nch0w** [comment]
Until there is consensus on which of the three navbars to use throughout, I cannot implement #3.

Fixes for most of the other issues will be pushed very shortly, although it might be a lot of work to refactor all of the id's and classes. I will also be fixing some bugs in the wordpairs page.

**Comment by LennyLip** [comment]
Thanks, @neilc314, ok, let's keep ids and classes in the current state.

**Comment by nch0w** [comment]
See #113 for the fixes
