### ISSUE TITLE
Minifying JavaScript and CSS bundles

### ISSUE THREAD

**Issue by LennyLip** [studyhub-co/physics-is-beautiful#114]
We need to minifying All JavaScript and CSS bundles in production mode.

**Comment by nch0w** [comment]
Should we use [this](https://github.com/django-compressor/django-compressor)?

**Comment by LennyLip** [comment]
@neilc314 no, the project is using [django-webpack-loader](https://github.com/owais/django-webpack-loader). So we need to configure webpack config with [uglifyjs-webpack-plugin](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) and [postcss-loader](https://github.com/postcss/postcss-loader)

For HTML we can use [spaceless ](https://docs.djangoproject.com/en/dev/ref/templates/builtins/?from=olddocs#spaceless) filter in base template 

Also, we need to enable gzip on EBS, [the link](https://gist.github.com/omidfi/aaae08617729d26fce52024cafb59e12) for example

**Comment by LennyLip** [comment]
It was realized
