### ISSUE TITLE
/discussion/users page is broken

### ISSUE THREAD

**Issue by nch0w** [studyhub-co/physics-is-beautiful#122]
However, it was working when the old djeddit fork was in use. Look to that for any potential bug fixes.

**Comment by LennyLip** [comment]
fixed 2a1e8eae89250dfb86c1175e5b92f55e44282ab7

**Comment by LennyLip** [comment]
Fixed.
We need to decide, do we really need users list page and if yes, then figure out where a link to this page should place on.

**Comment by nch0w** [comment]
I think we do need a users list page in case users need to be quickly banned, e.g. for abusing the discussion forum. It doesn't really matter where the link to this page should be placed as the page is only accessible by superusers. In the previous djeddit fork, I just placed a "User List" link at the footer of the page. [This](https://github.com/nscozzaro/physics-is-beautiful/blob/2f0e985d6c422333a1ed801ac7103c1dcd482092/templates/djeddit/base.html#L23-L25) is where it used to be.

**Comment by LennyLip** [comment]
@neilc314 ok, it would be nice if you copy paste this code in develop branch. If you think that we destroyed some of your templates changes, it would be nice if you copy paste this changes also if you think that they must be in the current development branch.
