### ISSUE TITLE
Editor server 500 error

### ISSUE THREAD

**Issue by LennyLip** [studyhub-co/physics-is-beautiful#123]
1. Go to /editor/ 
2. Select Curriculum studio tab
3. Select "Default Curriculum by Physics Is Beautiful"
4. Reselect None - start from scratch
5. Click "Create curriculum" 
got 500 server error

**Comment by nscozzaro** [comment]
We want to redesign this page so this won't be an issue. We can close this once that page is updated to be something like this:
![image](https://user-images.githubusercontent.com/15185105/44010848-f30a844a-9e82-11e8-962f-1b60a9e231a7.png)

**Comment by LennyLip** [comment]
500 server error is an issue in any case in no matter the client part.
