### ISSUE TITLE
Social login redirect and change login to use the email address instead of username

### ISSUE THREAD

**Issue by nscozzaro** [studyhub-co/physics-is-beautiful#13]
Eliminating the requirement of a username can hopefully resolve the issue that social login redirects to a page asking for a username. We want social login to take the user directly to the curriculum page.

**Comment by Nizebulous** [comment]
I just removed the username and changed authentication to use email.

**Comment by nscozzaro** [comment]
Successful login using social authentication should take the user directly to the curriculum page, but instead is still redirecting to a different page shown below. 

![image](https://cloud.githubusercontent.com/assets/15185105/23598264/5f759fa8-0207-11e7-91ed-46791b741145.png)

**Comment by Nizebulous** [comment]
Ok. I will look again. Django allauth is a bit irritating in how it works.

**Comment by Nizebulous** [comment]
I removed the requirement for the first name and last name fields. I am not sure if this fixes the redirect issue or not.

**Comment by Nizebulous** [comment]
The redirect is occurring because you already have an account with that email and it's unsafe to auto-merge. I have written a custom adapter that will auto-merge in the case where the email address has been verified, which should be safe.
