### ISSUE TITLE
Automatically update wsgi.conf

### ISSUE THREAD

**Issue by nch0w** [studyhub-co/physics-is-beautiful#148]
(instead of `$ cp /home/ec2-user/conf-save/wsgi.conf /etc/httpd/conf.d/wsgi.conf && apachectl restart`)

This should be the new `wsgi.conf`.

    LoadModule wsgi_module modules/mod_wsgi.so
    WSGIPythonHome /opt/python/run/baselinenv
    WSGISocketPrefix run/wsgi
    WSGIRestrictEmbedded On
    
    <VirtualHost *:80>
    
    Alias /media/ /opt/python/current/app/media/
    <Directory /opt/python/current/app/media/>
    Order allow,deny
    Allow from all
    </Directory>
    
    Alias /static/ /opt/python/current/app/collectedstatic/
    <Directory /opt/python/current/app/collectedstatic/>
    Order allow,deny
    Allow from all
    </Directory>
    
    Header always unset X-Frame-Options
    
    WSGIScriptAlias / /opt/python/current/app/pib/wsgi.py
    
    
    <Directory /opt/python/current/app/>
      Require all granted
    </Directory>
    
    WSGIDaemonProcess wsgi processes=1 threads=15 display-name=%{GROUP} \
      python-path=/opt/python/current/app:/opt/python/run/venv/lib64/python3.4/site-packages:/opt/python/run/venv/lib/python3.4/site-packages user=wsgi group=wsgi \
      home=/opt/python/current/app
    WSGIProcessGroup wsgi
    </VirtualHost>
    
    LogFormat "%h (%{X-Forwarded-For}i) %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

**Comment by LennyLip** [comment]
not actual due to amazon Linux v2 use Nginx.
