### ISSUE TITLE
Background music continues if using delete key to exit vector game

### ISSUE THREAD

**Issue by nscozzaro** [studyhub-co/physics-is-beautiful#52]

**Comment by Nizebulous** [comment]
@nscozzaro I need better steps to reproduce... The `delete` key doesn't exit the vector game for me (and I don't think it should.

**Comment by nscozzaro** [comment]
@Nizebulous On my computer in Chrome the delete/backspace key causes the browser to go back a page (after first pulling up the alert message). Since it didn't work for you I just tried alt-left arrow, which DID stop the music. This makes me think that it's an anomaly due to the chrome extension that I had to install to continue having the delete=back a page functionality after Chrome recently eliminated it, so let's ignore this.
