### ISSUE TITLE
Add styles to everything on /templates/allauth/account

### ISSUE THREAD

**Issue by nch0w** [studyhub-co/physics-is-beautiful#91]
For example, [this page](http://www.physicsisbeautiful.com/accounts/signup/).

**Comment by nscozzaro** [comment]
Correct me if I'm wrong, but we don't link to that page... the signup should be in the modal from the homepage, right? The email template we send out definitely needs styling though

**Comment by nch0w** [comment]
Steps to reproduce:
1. Click "create a profile" on /curriculum. (This should open the signup modal you mentioned.)
2. Enter any "incorrect" set of values into the form. For example, passwords that do not match.
3. Click "Sign up"
4. This takes you to /accounts/signup/ with any error messages, and it does not appear to have any styles.

**Comment by nscozzaro** [comment]
Interesting, yes this needs to be fixed.

**Comment by LennyLip** [comment]
Now, styles for register page is different on a home page and /curriculum/ page.

**Comment by nch0w** [comment]
@LennyLip The home page uses Bootstrap 4, while the /curriculum/ page uses Bootstrap 3. Once we get both to use the same version of bootstrap, this will be fixed.
